// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
  }
}

export { }
